"""
Django settings for logindjango project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Tüm hostlara izin ver

# CSRF Ayarları - DEBUG modunda tamamen devre dışı bırak
CSRF_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = None
CSRF_TRUSTED_ORIGINS = ['*']

# Güvenlik ayarları - SADECE GELIŞTIRME ORTAMI İÇİN!
if DEBUG:
    # CSRF korumasını tamamen devre dışı bırak
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SAMESITE = None
    CSRF_COOKIE_NAME = 'csrftoken'
    CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
    CSRF_USE_SESSIONS = False
    CSRF_TRUSTED_ORIGINS = ['*']
    
    # Security settings
    SESSION_COOKIE_SECURE = False
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_SSL_REDIRECT = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',  # Token authentication için
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'django_celery_beat',
    
    # Local apps
    'users',
    'ilan',
    'basvuru',
    'auth.apps.AuthenticationConfig', # Keep this one
    # 'authentication', # Remove the duplicate app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Debug modunda CSRF middleware'ını devre dışı bırak, prod ortamında aktif et
    'django.middleware.csrf.CsrfViewMiddleware' if not DEBUG else None,
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'logindjango.middleware.SwaggerPermissionMiddleware',  # Swagger izinleri için middleware
]

# None değerlerini listeden temizle
MIDDLEWARE = [middleware for middleware in MIDDLEWARE if middleware is not None]

ROOT_URLCONF = 'logindjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logindjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',         # PostgreSQL DB adı 'postgres'
        'USER': 'postgres',         # PostgreSQL kullanıcı adı
        'PASSWORD': '1036',         # PostgreSQL şifresi
        'HOST': 'localhost',        # PostgreSQL bağlantısı
        'PORT': '5432',             # PostgreSQL varsayılan portu
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Varsayılan olarak erişim izni verilir, güvenlik view bazında sağlanacak
    ],
    'PAGE_SIZE': 10
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),      # Access token ömrü 1 saat
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token ömrü 7 gün
    'ROTATE_REFRESH_TOKENS': True,                   # Refresh token'ı her kullanımda yenile
    'BLACKLIST_AFTER_ROTATION': False,               # Eski token'ları kara listeye al (Şimdilik devre dışı)
    'UPDATE_LAST_LOGIN': True,                      # Son giriş zamanını güncelle
    'ALGORITHM': 'HS256',                           # Token şifreleme algoritması
    'SIGNING_KEY': SECRET_KEY,                      # İmzalama anahtarı
    'VERIFYING_KEY': None,                          # Doğrulama anahtarı
    'AUDIENCE': None,                               # Hedef kitle
    'ISSUER': None,                                 # Sağlayıcı
    'AUTH_HEADER_TYPES': ('Bearer',),               # Yetkilendirme başlık türü
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',       # Yetkilendirme başlık adı
    'USER_ID_FIELD': 'id',                          # Kullanıcı kimlik alanı
    'USER_ID_CLAIM': 'user_id',                     # Token içindeki kullanıcı kimlik iddiası
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # Token sınıfları
    'TOKEN_TYPE_CLAIM': 'token_type',               # Token tür iddiası
    'JTI_CLAIM': 'jti',                            # JWT kimlik iddiası
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Tüm kaynaklara izin ver (sadece geliştirme ortamında kullanılmalı)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Frontend URL
    "http://127.0.0.1:5173",  # Frontend URL (alternatif)
    "http://localhost:3000",  # Alternatif frontend port
    "http://127.0.0.1:3000",  # Alternatif frontend port
    "http://localhost:5174",  # Vite dev server port
    "http://127.0.0.1:5174",  # Vite dev server port (alternatif)
]

# CSRF Güvenilir Kaynaklar
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
]

# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

AUTHENTICATION_BACKENDS = [
    'auth.backends.TCAuthenticationBackend', # Update path to the new location
    'django.contrib.auth.backends.ModelBackend', # Keep the default backend
]

# Swagger ayarları
SWAGGER_SETTINGS = {
   'SECURITY_DEFINITIONS': {
      'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"',
      }
   },
   'USE_SESSION_AUTH': False,
   'JSON_EDITOR': True,
   'PERSIST_AUTH': True,
   'REFETCH_SCHEMA_WITH_AUTH': True,
   'REFETCH_SCHEMA_ON_LOGOUT': True,
   'SHOW_REQUEST_HEADERS': True,
   'PUBLIC': True,
   'DEFAULT_AUTO_SCHEMA_CLASS': 'logindjango.yasg_settings.CustomSwaggerAutoSchema',
   'LOGIN_URL': '/admin/login/',
   'LOGOUT_URL': '/admin/logout/',
   'VALIDATOR_URL': None,
   'DOC_EXPANSION': 'list',
   'OPERATIONS_SORTER': 'alpha',
   'TAGS_SORTER': 'alpha',
}

# Swagger için özel izinler
SWAGGER_PUBLIC_PERMISSION_CLASSES = [
    'rest_framework.permissions.AllowAny',
]
