# Generated by Django 5.1.7 on 2025-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ilan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('status', models.CharField(choices=[('TASLAK', 'Taslak'), ('GONDERILDI', 'Gönderildi'), ('DEGERLENDIRILDI', 'Değerlendirildi'), ('KABUL_EDILDI', 'Kabul Edildi'), ('RED_EDILDI', 'Red Edildi')], default='TASLAK', max_length=20, verbose_name='Durum')),
                ('tablo5_file', models.FileField(blank=True, null=True, upload_to='tablo5/', verbose_name='Tablo 5 Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('aday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to=settings.AUTH_USER_MODEL, verbose_name='Aday')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ilan.ilan', verbose_name='İlan')),
            ],
            options={
                'verbose_name': 'Başvuru',
                'verbose_name_plural': 'Başvurular',
                'ordering': ['-submission_date'],
                'unique_together': {('ilan', 'aday')},
            },
        ),
        migrations.CreateModel(
            name='Belge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('YAYIN', 'Yayın'), ('PROJE', 'Proje'), ('PATENT', 'Patent'), ('DIGER', 'Diğer')], max_length=10, verbose_name='Tür')),
                ('file', models.FileField(upload_to='belgeler/', verbose_name='Dosya')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('is_main_author', models.BooleanField(default=False, verbose_name='Birinci Yazar mı?')),
                ('category', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=2, null=True, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('basvuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belgeler', to='basvuru.basvuru', verbose_name='Başvuru')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Tablo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='tablo5_files/', verbose_name='Dosya Yolu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('basvuru', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tablo5', to='basvuru.basvuru', verbose_name='Başvuru')),
            ],
            options={
                'verbose_name': 'Tablo 5',
                'verbose_name_plural': "Tablo 5'ler",
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Puan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Değer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('kriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puanlar', to='ilan.kriter', verbose_name='Kriter')),
                ('supporting_documents', models.ManyToManyField(related_name='puanlar', to='basvuru.belge', verbose_name='Destekleyici Belgeler')),
                ('tablo5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puanlar', to='basvuru.tablo5', verbose_name='Tablo 5')),
            ],
            options={
                'verbose_name': 'Puan',
                'verbose_name_plural': 'Puanlar',
                'ordering': ['kriter__ad'],
                'unique_together': {('tablo5', 'kriter')},
            },
        ),
    ]
