# Generated by Django 5.1.7 on 2025-03-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Ad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Fakülte',
                'verbose_name_plural': 'Fakülteler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Kriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Ad')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('puan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kriter',
                'verbose_name_plural': 'Kriterler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Ad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('fakulte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolumler', to='ilan.fakulte', verbose_name='Fakülte')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
                'ordering': ['fakulte__ad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('son_basvuru_tarihi', models.DateTimeField(verbose_name='Son Başvuru Tarihi')),
                ('status', models.CharField(choices=[('TASLAK', 'Taslak'), ('AKTIF', 'Aktif'), ('KAPALI', 'Kapalı')], default='TASLAK', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='ilan.bolum', verbose_name='Bölüm')),
                ('kriterler', models.ManyToManyField(related_name='ilanlar', to='ilan.kriter', verbose_name='Kriterler')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
