# Generated by Django 4.2.7 on 2025-03-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolum',
            options={'ordering': ['ad'], 'verbose_name': 'Bölüm', 'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AlterField(
            model_name='bolum',
            name='fakulte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolumler', to='ilan.fakulte', verbose_name='Fakülte'),
        ),
    ]
