# Generated by Django 5.1.7 on 2025-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fakülte'),
        ),
        migrations.AddField(
            model_name='user',
            name='tc_kimlik_no',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='TC Kimlik No'),
        ),
    ]
