# Generated by Django 5.1.7 on 2025-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department_user_faculty_user_tc_kimlik_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('YONETICI', 'Yönetici'), ('JURI_UYESI', 'Jüri Üyesi'), ('ADAY', 'Aday'), ('SUPERADMIN', 'Super Admin')], default='ADAY', max_length=20, verbose_name='Rol'),
        ),
    ]
