# Generated by Django 4.2.7 on 2025-03-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_aday_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tc_kimlik_no',
            field=models.CharField(default='', max_length=11, verbose_name='TC Kimlik No'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('tc_kimlik_no__isnull', False), models.Q(('tc_kimlik_no', ''), _negated=True)), fields=('tc_kimlik_no',), name='unique_tc_kimlik_no'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_email'),
        ),
    ]
